namespace Preagonal.GServer.Protocol;

public enum PlayerToServerPacketId : byte
{
    LevelWarp = 0,
    BoardModify = 1,
    PlayerProps = 2,
    ItemAdd = 12,
    ItemDelete = 13,
    ClaimPker = 14,
    BaddyProps = 15,
    BaddyHurt = 16,
    BaddyAdd = 17,
    OpenChest = 20,
    ShowImg = 24,
    PrivateMessage = 28,
    HurtPlayer = 26,
    NpcWeaponDelete = 29,
    LevelWarpMod = 30,
    ItemTake = 32,
    WeaponAdd = 33,
    TriggerAction = 38,
    ServerWarp = 41,
    RawData = 50,
    RcServerOptionsGet = 51,
    RcServerOptionsSet = 52,
    RcFolderConfigGet = 53,
    RcFolderConfigSet = 54,
    RcRespawnSet = 55,
    RcHorseLifeSet = 56,
    RcApIncrementSet = 57,
    RcBaddyRespawnSet = 58,
    RcPlayerPropsGet = 59,
    RcPlayerPropsSet = 60,
    RcDisconnectPlayer = 61,
    RcUpdateLevels = 62,
    RcAdminMessage = 63,
    RcPrivateAdminMessage = 64,
    RcListRemoteControls = 65,
    RcDisconnectRemoteControl = 66,
    RcApplyReason = 67,
    RcServerFlagsGet = 68,
    RcServerFlagsSet = 69,
    RcAccountAdd = 70,
    RcAccountDelete = 71,
    RcAccountListGet = 72,
    RcPlayerPropsGetById = 73,
    RcPlayerPropsGetByAccount = 74,
    RcPlayerPropsReset = 75,
    RcPlayerPropsSetById = 76,
    RcAccountGet = 77,
    RcAccountSet = 78,
    RcChat = 79,
    RcWarpPlayer = 82,
    RcPlayerRightsGet = 83,
    RcPlayerRightsSet = 84,
    RcPlayerCommentsGet = 85,
    RcPlayerCommentsSet = 86,
    RcPlayerBanGet = 87,
    RcPlayerBanSet = 88,
    RcFileBrowserStart = 89,
    RcFileBrowserChangeDirectory = 90,
    RcFileBrowserEnd = 91,
    RcFileBrowserDownload = 92,
    RcFileBrowserUpload = 93,
    RcFileBrowserMove = 96,
    RcFileBrowserDelete = 97,
    RcFileBrowserRename = 98,
    NcNpcGet = 103,
    NcNpcDelete = 104,
    NcNpcReset = 105,
    NcNpcScriptGet = 106,
    NcNpcWarp = 107,
    NcNpcFlagsGet = 108,
    NcNpcScriptSet = 109,
    NcNpcFlagsSet = 110,
    NcNpcAdd = 111,
    NcClassEdit = 112,
    NcClassAdd = 113,
    NcLocalNpcsGet = 114,
    NcWeaponListGet = 115,
    NcWeaponGet = 116,
    NcWeaponAdd = 117,
    NcWeaponDelete = 118,
    NcClassDelete = 119,
    NcLevelListGet = 150,
    NcLevelListSet = 151,
    RequestText = 152,
    SendText = 154,
    RcLargeFileStart = 155,
    RcLargeFileEnd = 156,
    UpdateGani = 157,
    RcFolderDelete = 160,
    RcUnknown162 = 162,
    SetEncryptionKey = 252,
    Bundle = 253
}

public enum ServerToPlayerPacketId : byte
{
    LevelBoard = 0,
    LevelLink = 1,
    BaddyProps = 2,
    NpcProps = 3,
    LevelChest = 4,
    LevelSign = 5,
    LevelName = 6,
    BoardModify = 7,
    OtherPlayerProps = 8,
    PlayerProps = 9,
    IsLeader = 10,
    BombAdd = 11,
    BombDelete = 12,
    PlayerWarp = 14,
    WarpFailed = 15,
    DisconnectMessage = 16,
    HorseAdd = 17,
    HorseDelete = 18,
    ArrowAdd = 19,
    ItemAdd = 22,
    ItemDelete = 23,
    NpcMoved = 24,
    Signature = 25,
    NpcAction = 26,
    BaddyHurt = 27,
    FlagSet = 28,
    NpcDelete = 29,
    FileSendFailed = 30,
    ShowImg = 32,
    NpcWeaponAdd = 33,
    NpcWeaponDelete = 34,
    RcAdminMessage = 35,
    Explosion = 36,
    PrivateMessage = 37,
    LevelModTime = 39,
    HurtPlayer = 40,
    NewWorldTime = 42,
    DefaultWeapon = 43,
    FileUpToDate = 45,
    HitObjects = 46,
    StaffGuilds = 47,
    TriggerAction = 48,
    PlayerWarp2 = 49,
    RcAccountAdd = 50,
    RcAccountStatus = 51,
    RcAccountName = 52,
    RcAccountDelete = 53,
    RcAccountProperties = 54,
    AddPlayer = 55,
    DeletePlayer = 56,
    RcAccountPropertiesGet = 57,
    RcAccountChange = 58,
    RcPlayerPropertiesChange = 59,
    RcServerFlagsGet = 61,
    RcPlayerRightsGet = 62,
    RcPlayerCommentsGet = 63,
    RcPlayerBanGet = 64,
    RcFileBrowserDirList = 65,
    RcFileBrowserDir = 66,
    RcFileBrowserMessage = 67,
    LargeFileStart = 68,
    LargeFileEnd = 69,
    RcAccountListGet = 70,
    RcPlayerProperties = 71,
    RcPlayerPropertiesGet = 72,
    RcAccountGet = 73,
    RcChat = 74,
    RcServerOptionsGet = 76,
    RcFolderConfigGet = 77,
    NcControl = 78,
    NpcServerAddress = 79,
    NcLevelList = 80,
    LargeFileSize = 84,
    RawData = 100,
    BoardPacket = 101,
    File = 102,
    RcMaxUploadFileSize = 103,
    UpdatePackageSize = 105,
    UpdatePackageDone = 106,
    BoardLayer = 107,
    NpcBytecode = 131,
    GaniScript = 134,
    NpcWeaponScript = 140,
    NpcDelete2 = 150,
    Say2 = 153,
    SetActiveLevel = 156,
    NcNpcAttributes = 157,
    NcNpcAdd = 158,
    NcNpcDelete = 159,
    NcNpcScript = 160,
    NcNpcFlags = 161,
    NcClassGet = 162,
    NcClassAdd = 163,
    NcLevelDump = 164,
    NcWeaponListGet = 167,
    Unknown168 = 168,
    GhostIcon = 174,
    Shoot = 175,
    ServerWarp = 178,
    StatusList = 180,
    UpdatePackageIsUpdated = 187,
    Shoot2 = 191,
    NcClassDelete = 188,
    ServerListConnected = 190,
    NcWeaponGet = 192,
    ClearWeapons = 194,
    LoadGani = 195,
    SetEncryptionKey = 252,
    Bundle = 253
}

public enum ServerToListServerPacketId : byte
{
    SetIp = 5,
    PlayerSet = 7,
    PlayerAdd = 14,
    PlayerRemove = 15,
    ServerInfo = 18,
    Ping = 16,
    VerifyAccount2 = 17,
    NewServer = 22,
    ServerHqPass = 23,
    ServerHqLevel = 24,
    RequestList = 26,
    RegisterV3 = 30,
    SendText = 31
}

public enum ListServerToServerPacketId : byte
{
    ErrorMessage = 8,
    VerifyAccount2 = 11,
    ServerInfo = 18,
    RequestText = 19,
    SendText = 20,
    AssignPcId = 25,
    Ping = 99
}

[Flags]
public enum PlayerSessionType
{
    Await = unchecked((int)0x80000000),
    Client = 1 << 0,
    RemoteControl = 1 << 1,
    NpcServer = 1 << 2,
    NpcControl = 1 << 3,
    Client2 = 1 << 4,
    Client3 = 1 << 5,
    RemoteControl2 = 1 << 6,
    External = 1 << 7,
    Web = 1 << 8,
    AnyClient = Client | Client2 | Client3 | Web,
    AnyRemoteControl = RemoteControl | RemoteControl2,
    AnyNpcControl = NpcControl,
    AnyControl = AnyRemoteControl | AnyNpcControl,
    AnyPlayer = AnyClient | AnyRemoteControl,
    NonIterable = NpcServer | AnyNpcControl | External
}

public enum EncryptionGeneration : uint
{
    Gen1 = 0,
    Gen2 = 1,
    Gen3 = 2,
    Gen4 = 3,
    Gen5 = 4,
    Gen6 = 5
}

public enum CompressionType : byte
{
    Uncompressed = 0x02,
    Zlib = 0x04,
    Bz2 = 0x06
}
